spring:
  profiles:
    active: local

  jpa:
    generate-ddl: true
    database: mysql

  # mysql datasource
  datasource:
    url: jdbc:mysql://localhost:3306/return_home_safely?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yeollow
    password: yeollow

  #kafka producer properties
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer    # LongSerializer class in org.apache.kafka.common.serialization package
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer   # JsonSerializer class in org.springframework.kafka.support.serializer package
      client-id: return-home-safely-producer
      acks: 1

    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer    # LongDeserializer class in org.apache.kafka.common.serialization package
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer   # JsonDeserializer class in org.springframework.kafka.support.serializer package
      group-id: return-home-safely-consumer
      enable-auto-commit: true
      auto-offset-reset: latest


    template:
      default-topic: KafkaBatchProducer    # default topic.

server:
  port: 7070
