spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:batchTable
    driver-class-name: org.h2.Driver
    username: yeollow
    password: yeollow

  h2:
    console:
      enabled: true

#kafka producer properties
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer    # LongSerializer class in org.apache.kafka.common.serialization package
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer   # JsonSerializer class in org.springframework.kafka.support.serializer package
      client-id: KafkaItemWriter
      acks: 1

    template:
      default-topic: KafkaBatchProducer    # default topic.


server:
  port: 7070


